(() => {
  'use strict';
  if (window.__tcQuotationRecordsLoaded) return;
  window.__tcQuotationRecordsLoaded = true;
  const API_BASE = 'https://terajucibina.vercel.app';
  const params = new URLSearchParams(location.search);
  const plannerType = /renovationplanner\.html?$/i.test(location.pathname) ? 'renovation' : ((params.get('plannerType') || 'build').toLowerCase() === 'renovation' ? 'renovation' : 'build');
  const role = (params.get('audience') || document.body.dataset.role || 'homeowner').toLowerCase() === 'contractor' ? 'contractor' : 'homeowner';
  const idKey = role === 'contractor' ? 'contractorId' : 'homeownerId';
  const storageKey = `teraju.${role}.github.v1`;
  const projectStorageKey = `teraju.${role}.${plannerType}.projectId.v1`;
  let activeId = (params.get(idKey) || '').trim().toUpperCase();
  let currentQuotationId = params.get('quotationId') || '';
  let currentQuotationNumber = '';
  let currentProjectId = '';
  let currentQuotationType = '';
  let restoring = false;
  let quotationCache = null;
  function localAccount() { try { return JSON.parse(localStorage.getItem(storageKey) || 'null'); } catch { return null; } }
  if (!activeId) activeId = String(localAccount()?.[idKey] || '').trim().toUpperCase();
  if (!activeId) return;
  function trackEvent(name, extra = {}) { try { if (typeof window.TERAJU_GA_EVENT === 'function') window.TERAJU_GA_EVENT(name, Object.fromEntries(Object.entries({role, planner_type:plannerType, ...extra}).filter(([,v]) => v !== undefined && v !== ''))); } catch {} }
  function apiUrl() { return `${API_BASE}/api/quotations`; }
  async function request(method, body) {
    let url = apiUrl();
    if (method === 'GET') url += `?role=${encodeURIComponent(role)}&id=${encodeURIComponent(activeId)}&plannerType=${encodeURIComponent(plannerType)}`;
    const response = await fetch(url, { method, headers: body ? {'Content-Type':'application/json'} : undefined, body: body ? JSON.stringify(body) : undefined }).catch(() => null);
    if (!response) throw new Error('Unable to reach the quotation service.');
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.message || 'Quotation request failed.');
    return data;
  }
  function mapEntries(map) { return map instanceof Map ? [...map.entries()] : []; }
  function selectedQuotationType() { return document.querySelector('input[name="quotationType"]:checked')?.value === 'detail' ? 'detail' : 'simple'; }
  function makeProjectId() { const prefix = plannerType === 'renovation' ? 'PRJ-REN' : 'PRJ-BLD'; return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`; }
  function ensureProjectId() {
    if (!currentProjectId) { try { currentProjectId = String(localStorage.getItem(projectStorageKey) || '').trim(); } catch {} }
    if (!currentProjectId) currentProjectId = makeProjectId();
    try { localStorage.setItem(projectStorageKey, currentProjectId); } catch {}
    return currentProjectId;
  }
  function snapshotPlanner() {
    const rooms = [...document.querySelectorAll('#roomsContainer .room-card')].map(room => ({id:room.id,type:room.querySelector('.room-type')?.value||'other',name:room.querySelector('.room-name')?.value||'',area:room.querySelector('.room-area')?.value||''}));
    return {customerName:document.getElementById('customerName')?.value||'',projectLocation:document.getElementById('projectLocation')?.value||'',builtUpArea:document.getElementById('builtUpArea')?.value||'',rooms,rates:typeof RATES!=='undefined'?{...RATES}:{},customRates:typeof customRates!=='undefined'?mapEntries(customRates):[],customQuantities:typeof customQuantities!=='undefined'?mapEntries(customQuantities):[],customDescriptions:typeof customDescriptions!=='undefined'?mapEntries(customDescriptions):[],customRoomLabels:typeof customRoomLabels!=='undefined'?mapEntries(customRoomLabels):[],excludedItems:typeof excludedItems!=='undefined'?[...excludedItems]:[],manualItems:typeof manualItems!=='undefined'?[...manualItems.entries()]:[],standardRateItems:typeof standardRateItems!=='undefined'?[...standardRateItems]:[],quotationType:selectedQuotationType(),projectId:ensureProjectId()};
  }
  function currentTotal(){try{return Number(getCurrentQuotationData()?.total||0)}catch{return Number(document.getElementById('grandTotal')?.textContent?.replace(/[^0-9.-]/g,'')||0)}}
  function buildQuotationRecord(){
    const type=selectedQuotationType(); const customer=document.getElementById('customerName')?.value?.trim()||'Not specified'; const location=document.getElementById('projectLocation')?.value?.trim()||'Not specified'; const now=new Date().toISOString(); const prefix=plannerType==='renovation'?'QT-REN':'QT-BLD'; const fallbackNumber=plannerType==='renovation'?`NR-QO${Date.now().toString().slice(-4)}`:`NB-QO${Date.now().toString().slice(-4)}`; const qId=currentQuotationId||`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`; const qNumber=currentQuotationNumber||(typeof quotationNumber!=='undefined'&&quotationNumber?quotationNumber:fallbackNumber); const plannerState=snapshotPlanner();
    return {schemaVersion:1,recordType:'quotation',quotationId:qId,projectId:ensureProjectId(),quotationNumber:qNumber,plannerType,role,[idKey]:activeId,state:'final',quotationType:type,client:{name:customer},project:{location,builtUpArea:Number(plannerState.builtUpArea)||0},total:Number(currentTotal().toFixed(2)),plannerState,createdAt:now,updatedAt:now};
  }
  function injectStyles(){ if(document.getElementById('tc-quotation-records-style'))return; const style=document.createElement('style');style.id='tc-quotation-records-style';style.textContent=`.tc-quotation-tools{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:12px}.tc-quotation-btn{border:1px solid #d1d5db;background:#fff;color:#111827;border-radius:11px;padding:9px 13px;font-size:12px;font-weight:700;cursor:pointer;transition:.18s ease;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;min-height:42px}.tc-quotation-btn:hover{background:#f8fafc;border-color:#9ca3af;transform:translateY(-1px)}.tc-quotation-btn.primary{background:#111827;color:#fff;border-color:#111827}.tc-quotation-btn.primary:hover{background:#000}.tc-quotation-status{font-size:12px;color:#6b7280;min-height:18px}.tc-quotation-toast{position:fixed;right:18px;bottom:18px;z-index:10000;background:#111827;color:#fff;padding:12px 15px;border-radius:12px;box-shadow:0 14px 35px rgba(0,0,0,.2);font-size:13px;font-weight:700;opacity:0;transform:translateY(10px);pointer-events:none;transition:.2s ease}.tc-quotation-toast.show{opacity:1;transform:none}@media(max-width:767px){.tc-quotation-tools{display:grid;grid-template-columns:1fr 1fr}.tc-quotation-btn{width:100%}.tc-quotation-tools .tc-quotation-status{grid-column:1/-1}}`; document.head.appendChild(style); }
  function toast(message,error=false){let el=document.getElementById('tcQuotationToast');if(!el){el=document.createElement('div');el.id='tcQuotationToast';el.className='tc-quotation-toast';document.body.appendChild(el)}el.textContent=message;el.style.background=error?'#991b1b':'#111827';el.classList.add('show');clearTimeout(el.__timer);el.__timer=setTimeout(()=>el.classList.remove('show'),2400)}
  function quotationsUrl(){return `quotations.html?role=${encodeURIComponent(role)}&id=${encodeURIComponent(activeId)}&plannerType=${encodeURIComponent(plannerType)}`;}
  function addPlannerControls(){ injectStyles(); const actions=document.getElementById('quotationPrintActions'); if(actions&&!document.getElementById('tcSaveQuotation')){const wrap=document.createElement('div');wrap.className='tc-quotation-tools';wrap.innerHTML=`<button id="tcSaveQuotation" type="button" class="tc-quotation-btn primary">Save Quotation</button><a class="tc-quotation-btn" href="${quotationsUrl()}">My Quotations</a><span id="tcQuotationStatus" class="tc-quotation-status"></span>`;actions.insertBefore(wrap,actions.firstChild);document.getElementById('tcSaveQuotation').addEventListener('click',()=>saveQuotation(true))} }
  async function fetchQuotations(){ const data=await request('GET'); quotationCache=Array.isArray(data.quotations)?data.quotations:[]; return quotationCache; }
  async function switchQuotationVersion(type){
    if(restoring || type === currentQuotationType) return; ensureProjectId();
    try { const list = quotationCache || await fetchQuotations(); const match = list.find(item => item && item.plannerType === plannerType && item.projectId === currentProjectId && (item.quotationType || item.plannerState?.quotationType || 'simple') === type); currentQuotationType = type; if (match) { currentQuotationId = match.quotationId || ''; currentQuotationNumber = match.quotationNumber || ''; try { if (typeof quotationNumber !== 'undefined' && currentQuotationNumber) quotationNumber = currentQuotationNumber; } catch {} toast(`${type === 'detail' ? 'Detail' : 'Simple'} quotation selected.`); } else { currentQuotationId = ''; currentQuotationNumber = ''; toast(`${type === 'detail' ? 'Detail' : 'Simple'} quotation will be saved as a separate version.`); } } catch(error) { currentQuotationType = type; currentQuotationId = ''; currentQuotationNumber = ''; console.error(error); }
  }
  function bindQuotationType(){ document.querySelectorAll('input[name="quotationType"]').forEach(input=>{if(input.__tcBound)return;input.__tcBound=true;input.addEventListener('change',()=>switchQuotationVersion(selectedQuotationType()))}); }
  async function saveQuotation(showMessage=false){
    if(restoring||!document.getElementById('quotationDocument')||document.getElementById('quotationDocument').classList.contains('hidden'))return;
    const isNewQuotation = !currentQuotationId;
    ensureProjectId(); const record=buildQuotationRecord(); currentQuotationId=record.quotationId; currentQuotationNumber=record.quotationNumber; currentQuotationType=record.quotationType;
    const button=document.getElementById('tcSaveQuotation'),status=document.getElementById('tcQuotationStatus');if(button){button.disabled=true;button.textContent='Saving…'}if(status)status.textContent='Saving quotation…';
    try {
      const result=await request('PUT',{role,id:activeId,plannerType,quotation:record});
      const saved=result?.quotation||record;
      currentQuotationId=saved.quotationId||currentQuotationId;
      currentQuotationNumber=saved.quotationNumber||currentQuotationNumber;
      currentQuotationType=saved.quotationType||currentQuotationType;
      try { if (saved.quotationNumber && typeof quotationNumber !== 'undefined') quotationNumber=saved.quotationNumber; } catch {}
      quotationCache=null;
      const url=new URL(location.href);url.searchParams.set('quotationId',currentQuotationId);history.replaceState({},'',url.toString());
      if (isNewQuotation) trackEvent('quotation_created', {quotation_id:currentQuotationId, quotation_number:currentQuotationNumber, quotation_type:currentQuotationType === 'detail' ? 'detailed' : 'simple', total:Number(saved.total ?? record.total)});
      if(showMessage)toast(`${currentQuotationType==='detail'?'Detail':'Simple'} quotation ${currentQuotationNumber||''} saved successfully.`);
      if(status)status.textContent=`Saved ${currentQuotationNumber||''} · ${new Date().toLocaleTimeString('en-MY',{hour:'2-digit',minute:'2-digit'})}`;
    } catch(error) { if(showMessage)toast(error.message||'Unable to save quotation.',true);if(status)status.textContent='Save failed';console.error(error) } finally { if(button){button.disabled=false;button.textContent='Save Quotation'} }
  }
  function wrapGenerate(){ if(typeof window.generateQuotation!=='function'||window.generateQuotation.__tcWrapped)return false; const original=window.generateQuotation;const wrapped=function(){const result=original.apply(this,arguments);if(result!==false){currentQuotationType=selectedQuotationType();currentQuotationNumber=typeof quotationNumber!=='undefined'?quotationNumber:currentQuotationNumber;setTimeout(()=>saveQuotation(false),250)}return result};wrapped.__tcWrapped=true;wrapped.__tcOriginal=original;window.generateQuotation=wrapped;return true; }
  function setRoomField(room,selector,value){const el=room?.querySelector(selector);if(el&&value!==undefined)el.value=value;}
  function restoreSnapshot(state){ if(!state)return;restoring=true;try{if(state.projectId){currentProjectId=String(state.projectId);try{localStorage.setItem(projectStorageKey,currentProjectId)}catch{}}if(document.getElementById('customerName'))document.getElementById('customerName').value=state.customerName||'';if(document.getElementById('projectLocation'))document.getElementById('projectLocation').value=state.projectLocation||'';if(document.getElementById('builtUpArea'))document.getElementById('builtUpArea').value=state.builtUpArea||'';if(typeof RATES!=='undefined'&&RATES&&typeof RATES==='object')Object.assign(RATES,state.rates||{});if(typeof restoreMap==='function'){restoreMap(customRates,state.customRates);restoreMap(customQuantities,state.customQuantities);restoreMap(customDescriptions,state.customDescriptions);restoreMap(customRoomLabels,state.customRoomLabels)}if(typeof excludedItems!=='undefined'){excludedItems.clear();(state.excludedItems||[]).forEach(x=>excludedItems.add(x))}if(typeof manualItems!=='undefined'){manualItems.clear();(state.manualItems||[]).forEach(([k,v])=>manualItems.set(k,v))}if(typeof standardRateItems!=='undefined'&&Array.isArray(standardRateItems)){standardRateItems.length=0;(Array.isArray(state.standardRateItems)?state.standardRateItems:[]).forEach(item=>standardRateItems.push(item));}const container=document.getElementById('roomsContainer');if(container)container.innerHTML='';let previousCount=typeof roomCounter!=='undefined'?Number(roomCounter)||0:0;(state.rooms||[]).forEach(roomData=>{if(typeof addRoom!=='function')return;const before=container?[...container.querySelectorAll('.room-card')]:[];addRoom(roomData.type||'other');const after=container?[...container.querySelectorAll('.room-card')]:[];const room=after.length>before.length?after[after.length-1]:null;if(!room)return;room.id=roomData.id||room.id;setRoomField(room,'.room-type',roomData.type||'other');setRoomField(room,'.room-name',roomData.name||'');setRoomField(room,'.room-area',roomData.area||'')});if(typeof roomCounter!=='undefined'){const ids=[...(container?.querySelectorAll('.room-card')||[])].map(x=>x.id);const maxSuffix=ids.reduce((m,id)=>Math.max(m,Number((String(id).match(/(\d+)$/)||[])[1])||0),0);roomCounter=Math.max(previousCount,maxSuffix,ids.length)}const q=document.querySelector(`input[name="quotationType"][value="${state.quotationType==='detail'?'detail':'simple'}"]`);if(q){q.checked=true;q.dispatchEvent(new Event('change',{bubbles:true}))}if(typeof updateRoomsEmptyState==='function')updateRoomsEmptyState();if(typeof updateEstimate==='function')updateEstimate();}finally{restoring=false} }
  async function loadQuotationForEdit(){ if(!currentQuotationId)return;try{const data=await fetchQuotations();const quotation=data.find(item=>item?.quotationId===currentQuotationId);if(!quotation){toast('Quotation record not found.',true);return}currentQuotationNumber=quotation.quotationNumber||'';currentQuotationType=quotation.quotationType||quotation.plannerState?.quotationType||'simple';currentProjectId=String(quotation.projectId||quotation.plannerState?.projectId||`LEGACY-${plannerType}-${quotation.quotationId}`);try{localStorage.setItem(projectStorageKey,currentProjectId)}catch{}const savedState=quotation.plannerState||{};const savedRooms=Array.isArray(savedState.rooms)?savedState.rooms:[];restoreSnapshot(savedState);try{if(currentQuotationNumber&&typeof quotationNumber!=='undefined')quotationNumber=currentQuotationNumber}catch{}const type=currentQuotationType;const input=document.querySelector(`input[name="quotationType"][value="${type}"]`);if(input){input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}))}const roomsMatch=()=>{const cards=[...(document.querySelectorAll('#roomsContainer .room-card')||[])];if(cards.length!==savedRooms.length)return false;return savedRooms.every((roomData,index)=>String(cards[index]?.querySelector('.room-area')?.value??'')===String(roomData.area??'')&&String(cards[index]?.querySelector('.room-type')?.value??'')===String(roomData.type||'other'))};if(savedRooms.length&&!roomsMatch()){setTimeout(()=>{if(!roomsMatch())restoreSnapshot(savedState)},150)}trackEvent('quotation_opened', {quotation_id:quotation.quotationId, quotation_number:currentQuotationNumber, quotation_type:currentQuotationType === 'detail' ? 'detailed' : 'simple'});toast(`Quotation ${currentQuotationNumber||currentQuotationId} loaded.`)}catch(error){console.error(error);toast(error.message||'Unable to load quotation.',true)} }
  function init(){ if(!document.getElementById('quotationGenerator'))return; ensureProjectId();currentQuotationType=selectedQuotationType();injectStyles();addPlannerControls();bindQuotationType();if(!wrapGenerate())setTimeout(wrapGenerate,500);if(currentQuotationId)setTimeout(loadQuotationForEdit,900);const observer=new MutationObserver(()=>{addPlannerControls();bindQuotationType();wrapGenerate()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),20000); }
  window.tcQuotationRecords={saveQuotation,loadQuotationForEdit};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
