export default async function handler(req,res){
  const origin='https://terajuciptabina-eng.github.io';
  res.setHeader('Access-Control-Allow-Origin',origin);
  res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Admin-Key,X-Admin-Username,X-Admin-Password');
  res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');
  res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');
  if(req.method==='OPTIONS')return res.status(200).end();
  if(!['GET','POST','PUT','DELETE'].includes(req.method))return res.status(405).json({message:'Method not allowed.'});
  const repo=process.env.GITHUB_REPO||'terajuciptabina-eng/terajuciptabina',rulesPath='quotation/admin-calculation-rules.html',uiPath='quotation/shared/calculation-rules-ui.css',token=process.env.GITHUB_TOKEN;
  const expectedUser=String(process.env.ADMIN_USERNAME||'admin').trim(),expectedPass=String(process.env.ADMIN_PASSWORD||process.env.ADMIN_KEY||'').trim();
  const suppliedUser=String(req.headers['x-admin-username']||'').trim(),suppliedPass=String(req.headers['x-admin-password']||req.headers['x-admin-key']||'').trim();
  const isUI=String(req.query?.ui||'')==='1',protectedRead=req.method==='GET'&&String(req.query?.admin||'')==='1',hasCredentials=!!(suppliedUser||suppliedPass);
  const requiresAuth=isUI?(req.method!=='GET'):(req.method!=='GET'||protectedRead||hasCredentials);
  if(requiresAuth&&(!expectedPass||suppliedPass!==expectedPass||suppliedUser!==expectedUser))return res.status(401).json({message:'Invalid Admin username or password.'});
  const apiBase=`https://api.github.com/repos/${repo}`;
  const headers={Authorization:`Bearer ${token||''}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
  async function githubFile(path,options={}){const r=await fetch(`${apiBase}/contents/${path}`,{...options,headers:{...headers,...(options.headers||{})},cache:'no-store'});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}return{r,d}}
  const UI_KEYS=['item','description','method','coefficient','formula','unit','basis','note','actions'],UI_DEFAULT={item:'15%',description:'22%',method:'10%',coefficient:'11%',formula:'12%',unit:'6%',basis:'10%',note:'7%',actions:'7%'};
  function parseUI(s){const o={};for(const k of UI_KEYS){const m=s.match(new RegExp(`--cr-col-${k}\\s*:\\s*([^;]+);`));o[k]=m?String(m[1]).trim():UI_DEFAULT[k];if(!/^\\d+(?:\\.\\d+)?%$/.test(o[k]))o[k]=UI_DEFAULT[k]}return o}
  function normaliseUI(input){const n=UI_KEYS.map(k=>{const v=Number(String(input?.[k]??'').replace('%',''));return Number.isFinite(v)&&v>0?v:null});if(n.some(v=>v===null))throw Error('Invalid Calculation Rules UI column width.');const total=n.reduce((a,b)=>a+b,0),o={};let used=0;UI_KEYS.forEach((k,i)=>{if(i===UI_KEYS.length-1)o[k]=(100-used).toFixed(2)+'%';else{o[k]=(n[i]/total*100).toFixed(2)+'%';used+=Number(o[k].replace('%',''))}});return o}
  function writeUI(s,w){let n=s;for(const k of UI_KEYS){const re=new RegExp(`(--cr-col-${k}\\s*:\\s*)[^;]+(;?)`);if(!re.test(n))throw Error(`Shared Calculation Rules UI variable is missing: ${k}.`);n=n.replace(re,`$1${w[k]}$2`)}return n}
  function locate(s){const m=/(?:const|let)\s+rules\s*=\s*\[/.exec(s);if(!m)throw Error('Calculation Rules source array not found.');const startArray=s.indexOf('[',m.index);let depth=0,quote='',esc=false,template=false;for(let i=startArray;i<s.length;i++){const c=s[i];if(esc){esc=false;continue}if(quote){if(c==='\\')esc=true;else if(c===quote)quote='';continue}if(template){if(c==='\\')esc=true;else if(c==='`')template=false;continue}if(c==='\''||c==='"'){quote=c;continue}if(c==='`'){template=true;continue}if(c==='['){depth++;continue}if(c===']'){depth--;if(depth===0){let end=i+1;while(end<s.length&&/\s/.test(s[end]))end++;if(s[end]===';')end++;return{start:m.index,length:end-m.index,array:s.slice(startArray,i+1)}}}}throw Error('Calculation Rules source array is incomplete.')}
  function parse(s){const p=locate(s),raw=Function(`"use strict";return (${p.array});`)();if(!Array.isArray(raw)||!raw.length)throw Error('Calculation Rules source array is empty.');const rules=raw.map((x,i)=>Array.isArray(x)?{group:x[0]||'',path:x[1]||'',description:x[2]||'',method:x[3]||'',coefficient:x[4]||'',formula:x[5]||'',output:x[6]||'',basis:x[7]||'',note:x[8]||'',_index:i}:x&&typeof x==='object'?{...x,_index:i}:null).filter(Boolean);return{rules,start:p.start,length:p.length}}
  const groups=['PRELIMINARIES','STRUCTURES','ARCHITECTURES','ELECTRICAL','DOORS & WINDOWS','EXTERNAL WORK'],fields=['group','path','description','method','coefficient','formula','output','basis','note'];
  const clean=b=>Object.fromEntries(fields.map(f=>[f,String(b?.[f]??'').trim()]));
  function validate(r){if(!groups.includes(r.group))return'Valid group is required.';for(const f of fields.slice(1,8))if(!r[f])return`${f} is required.`;return''}
  const asSource=a=>a.map(r=>[r.group,r.path,r.description,r.method,r.coefficient,r.formula,r.output,r.basis,r.note||'']);
  const normPath=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim().toUpperCase();
  try{
    if(isUI){const cur=await githubFile(uiPath);if(!cur.r.ok)return res.status(cur.r.status).json({message:cur.d?.message||'Unable to read shared Calculation Rules UI standard.'});const source=Buffer.from(cur.d?.content||'','base64').toString('utf8');if(req.method==='GET')return res.status(200).json({ok:true,columnWidths:parseUI(source),sourceSha:cur.d?.sha||null});if(req.method!=='PUT')return res.status(405).json({message:'Calculation Rules UI supports GET and PUT only.'});const w=normaliseUI((typeof req.body==='string'?JSON.parse(req.body||'{}'):req.body||{}).columnWidths||{}),next=writeUI(source,w),saved=await githubFile(uiPath,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Update Calculation Rules global UI column widths',content:Buffer.from(next).toString('base64'),sha:cur.d.sha})});if(!saved.r.ok)return res.status(saved.r.status).json({message:saved.d?.message||'Unable to save shared Calculation Rules UI standard.'});return res.status(200).json({ok:true,columnWidths:w,message:'Calculation Rules UI column widths saved as the global default.'})}
    const cur=await githubFile(rulesPath);if(!cur.r.ok)return res.status(cur.r.status).json({message:cur.d?.message||'Unable to read Calculation Rules.'});const source=Buffer.from(cur.d?.content||'','base64').toString('utf8'),p=parse(source);let next=p.rules.map(({_index,...r})=>r);
    if(req.method==='GET')return res.status(200).json({ok:true,count:next.length,rules:next});
    const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});
    if(req.method==='DELETE'){
      const target=String(body.path||'').trim(),key=normPath(target);let i=next.findIndex(x=>normPath(x.path)===key);
      if(i<0&&key.split('/').length===1){const matches=next.map((x,j)=>({x,j})).filter(v=>normPath(v.x.path).endsWith('/ '+key)||normPath(v.x.path).endsWith('/'+key));if(matches.length===1)i=matches[0].j}
      if(i<0)return res.status(404).json({message:'Calculation Rule not found.'});if(next.length===1)return res.status(400).json({message:'At least one global Calculation Rule must remain.'});const deleted=next[i];next.splice(i,1);
      const replacement=`let rules=${JSON.stringify(asSource(next),null,2)};`,nextSource=source.slice(0,p.start)+replacement+source.slice(p.start+p.length),saved=await githubFile(rulesPath,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Permanently delete calculation rule: ${deleted.path}`,content:Buffer.from(nextSource).toString('base64'),sha:cur.d?.sha})});
      if(!saved.r.ok)return res.status(saved.r.status).json({message:saved.d?.message||'Unable to permanently delete Calculation Rule.'});return res.status(200).json({ok:true,deleted,message:'Calculation Rule permanently deleted from the global master source.',remaining:next.length});
    }
    const rule=clean(body.rule||body),error=validate(rule);if(error)return res.status(400).json({message:error});let i=-1,action=req.method==='POST'?'add':'edit';
    if(req.method==='POST'){if(next.some(x=>normPath(x.path)===normPath(rule.path)))return res.status(409).json({message:'A Calculation Rule with this path already exists.'});next.push(rule)}else{i=next.findIndex(x=>normPath(x.path)===normPath(body.originalPath));if(i<0)return res.status(404).json({message:'Original Calculation Rule not found.'});next[i]=rule}
    const replacement=`let rules=${JSON.stringify(asSource(next),null,2)};`,nextSource=source.slice(0,p.start)+replacement+source.slice(p.start+p.length),saved=await githubFile(rulesPath,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`${action==='add'?'Add':'Edit'} calculation rule: ${rule.path}`,content:Buffer.from(nextSource).toString('base64'),sha:cur.d?.sha})});if(!saved.r.ok)return res.status(saved.r.status).json({message:saved.d?.message||`Unable to ${action} Calculation Rule.`});return res.status(200).json({ok:true,rule,remaining:next.length,message:`Calculation Rule ${action==='add'?'added':'updated'} in the global master source.`});
  }catch(e){console.error(e);return res.status(500).json({message:e.message||'Unable to update Calculation Rules.'})}
}